#!/bin/bash

docker build \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VERSION=`git describe --always --dirty` \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    -t $IMAGE_NAME .
